CREATE TABLE IF NOT EXISTS public.project_monthly_contribution_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
  monthly_cycle_id bigint NOT NULL REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  period_start date NOT NULL,
  period_end date NOT NULL,
  source_currency_code text NOT NULL,
  source_amount numeric(20, 6) NOT NULL,
  usd_equivalent_amount numeric(20, 2) NOT NULL,
  commitment_percentage numeric(5, 2) NOT NULL,
  calculated_contribution_amount numeric(20, 2) NOT NULL,
  source_reference text,
  notes text,
  status text NOT NULL DEFAULT 'submitted',
  submitted_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_monthly_contribution_submissions_currency_check CHECK (source_currency_code ~ '^[A-Z0-9]{3,12}$'),
  CONSTRAINT project_monthly_contribution_submissions_amounts_check CHECK (
    source_amount >= 0
    AND usd_equivalent_amount >= 0
    AND commitment_percentage >= 0
    AND calculated_contribution_amount >= 0
  ),
  CONSTRAINT project_monthly_contribution_submissions_period_check CHECK (period_end >= period_start),
  CONSTRAINT project_monthly_contribution_submissions_status_check CHECK (status IN ('submitted')),
  CONSTRAINT project_monthly_contribution_submissions_current_key UNIQUE (project_id, monthly_cycle_id)
);

CREATE INDEX IF NOT EXISTS idx_project_monthly_contribution_submissions_cycle
ON public.project_monthly_contribution_submissions (monthly_cycle_id, project_id);

CREATE INDEX IF NOT EXISTS idx_project_monthly_contribution_submissions_project
ON public.project_monthly_contribution_submissions (project_id, submitted_at DESC);

DROP TRIGGER IF EXISTS set_project_monthly_contribution_submissions_updated_at ON public.project_monthly_contribution_submissions;
CREATE TRIGGER set_project_monthly_contribution_submissions_updated_at
BEFORE UPDATE ON public.project_monthly_contribution_submissions
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.project_monthly_contribution_submissions ENABLE ROW LEVEL SECURITY;
