DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payout_rail') THEN
    CREATE TYPE public.payout_rail AS ENUM ('evm', 'solana', 'fiat_stub');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payout_route_status') THEN
    CREATE TYPE public.payout_route_status AS ENUM ('draft', 'active', 'disabled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payout_intent_status') THEN
    CREATE TYPE public.payout_intent_status AS ENUM ('draft', 'ready', 'batched', 'processing', 'paid', 'failed', 'cancelled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payout_batch_status') THEN
    CREATE TYPE public.payout_batch_status AS ENUM ('draft', 'ready', 'processing', 'completed', 'failed', 'cancelled');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payout_reconciliation_status') THEN
    CREATE TYPE public.payout_reconciliation_status AS ENUM ('pending', 'matched', 'mismatch', 'manual_review', 'resolved');
  END IF;
END
$$;

ALTER TABLE public.monthly_cycle_events
DROP CONSTRAINT IF EXISTS monthly_cycle_events_event_type_check;

ALTER TABLE public.monthly_cycle_events
ADD CONSTRAINT monthly_cycle_events_event_type_check CHECK (
  event_type IN (
    'lock_attempt',
    'lock_success',
    'lock_failure',
    'calculation_package_attempt',
    'calculation_package_success',
    'calculation_package_failure',
    'verification_review',
    'approval_review',
    'payout_intents_create_attempt',
    'payout_intents_create_success',
    'payout_intents_create_failure'
  )
);

CREATE TABLE IF NOT EXISTS public.user_payout_routes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  rail public.payout_rail NOT NULL,
  label text NOT NULL DEFAULT '',
  currency_code text NOT NULL DEFAULT 'USD',
  destination jsonb NOT NULL DEFAULT '{}',
  is_default boolean NOT NULL DEFAULT false,
  status public.payout_route_status NOT NULL DEFAULT 'draft',
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_payout_routes_currency_code_check CHECK (currency_code ~ '^[A-Z]{3,12}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_payout_routes_one_default_active
ON public.user_payout_routes (user_id)
WHERE is_default AND status = 'active';

CREATE INDEX IF NOT EXISTS idx_user_payout_routes_user_status
ON public.user_payout_routes (user_id, status, is_default DESC);

DROP TRIGGER IF EXISTS set_user_payout_routes_updated_at ON public.user_payout_routes;
CREATE TRIGGER set_user_payout_routes_updated_at
BEFORE UPDATE ON public.user_payout_routes
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.payout_intents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monthly_cycle_id bigint NOT NULL REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  source_result_id bigint REFERENCES public.zkas_published_user_results(id) ON UPDATE CASCADE ON DELETE SET NULL,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  payout_route_id bigint REFERENCES public.user_payout_routes(id) ON UPDATE CASCADE ON DELETE SET NULL,
  rail public.payout_rail,
  currency_code text NOT NULL DEFAULT 'USD',
  amount_usd numeric(20, 6) NOT NULL,
  status public.payout_intent_status NOT NULL DEFAULT 'draft',
  idempotency_key text NOT NULL UNIQUE,
  status_reason text,
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payout_intents_amount_usd_check CHECK (amount_usd >= 0),
  CONSTRAINT payout_intents_currency_code_check CHECK (currency_code ~ '^[A-Z]{3,12}$'),
  CONSTRAINT payout_intents_ready_route_check CHECK (
    status <> 'ready' OR payout_route_id IS NOT NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payout_intents_source_result
ON public.payout_intents (source_result_id)
WHERE source_result_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_payout_intents_cycle_status
ON public.payout_intents (monthly_cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_payout_intents_user_cycle
ON public.payout_intents (user_id, monthly_cycle_id DESC);

DROP TRIGGER IF EXISTS set_payout_intents_updated_at ON public.payout_intents;
CREATE TRIGGER set_payout_intents_updated_at
BEFORE UPDATE ON public.payout_intents
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.payout_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monthly_cycle_id bigint NOT NULL REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  rail public.payout_rail NOT NULL,
  currency_code text NOT NULL DEFAULT 'USD',
  status public.payout_batch_status NOT NULL DEFAULT 'draft',
  total_amount_usd numeric(20, 6) NOT NULL DEFAULT 0,
  intent_count integer NOT NULL DEFAULT 0,
  execution_payload jsonb NOT NULL DEFAULT '{}',
  execution_reference text,
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payout_batches_total_amount_usd_check CHECK (total_amount_usd >= 0),
  CONSTRAINT payout_batches_intent_count_check CHECK (intent_count >= 0),
  CONSTRAINT payout_batches_currency_code_check CHECK (currency_code ~ '^[A-Z]{3,12}$')
);

CREATE INDEX IF NOT EXISTS idx_payout_batches_cycle_status
ON public.payout_batches (monthly_cycle_id, status);

CREATE INDEX IF NOT EXISTS idx_payout_batches_rail_status
ON public.payout_batches (rail, status);

DROP TRIGGER IF EXISTS set_payout_batches_updated_at ON public.payout_batches;
CREATE TRIGGER set_payout_batches_updated_at
BEFORE UPDATE ON public.payout_batches
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE IF NOT EXISTS public.payout_batch_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_batch_id bigint NOT NULL REFERENCES public.payout_batches(id) ON UPDATE CASCADE ON DELETE CASCADE,
  payout_intent_id bigint NOT NULL REFERENCES public.payout_intents(id) ON UPDATE CASCADE ON DELETE CASCADE,
  position integer NOT NULL DEFAULT 0,
  amount_usd numeric(20, 6) NOT NULL,
  status public.payout_intent_status NOT NULL DEFAULT 'batched',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payout_batch_items_amount_usd_check CHECK (amount_usd >= 0),
  CONSTRAINT payout_batch_items_batch_intent_key UNIQUE (payout_batch_id, payout_intent_id),
  CONSTRAINT payout_batch_items_intent_key UNIQUE (payout_intent_id)
);

CREATE INDEX IF NOT EXISTS idx_payout_batch_items_batch_position
ON public.payout_batch_items (payout_batch_id, position);

CREATE TABLE IF NOT EXISTS public.payout_reconciliation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_intent_id bigint REFERENCES public.payout_intents(id) ON UPDATE CASCADE ON DELETE SET NULL,
  payout_batch_id bigint REFERENCES public.payout_batches(id) ON UPDATE CASCADE ON DELETE SET NULL,
  status public.payout_reconciliation_status NOT NULL DEFAULT 'pending',
  rail public.payout_rail,
  external_reference text,
  observed_amount_usd numeric(20, 6),
  metadata jsonb NOT NULL DEFAULT '{}',
  note text,
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT payout_reconciliation_events_observed_amount_check CHECK (
    observed_amount_usd IS NULL OR observed_amount_usd >= 0
  )
);

CREATE INDEX IF NOT EXISTS idx_payout_reconciliation_events_intent_created
ON public.payout_reconciliation_events (payout_intent_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_payout_reconciliation_events_batch_status
ON public.payout_reconciliation_events (payout_batch_id, status);

ALTER TABLE public.user_payout_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_batch_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_reconciliation_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_payout_routes_self_select ON public.user_payout_routes;
CREATE POLICY user_payout_routes_self_select
ON public.user_payout_routes
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS user_payout_routes_self_insert ON public.user_payout_routes;
CREATE POLICY user_payout_routes_self_insert
ON public.user_payout_routes
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_payout_routes_self_update ON public.user_payout_routes;
CREATE POLICY user_payout_routes_self_update
ON public.user_payout_routes
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS payout_intents_self_select ON public.payout_intents;
CREATE POLICY payout_intents_self_select
ON public.payout_intents
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS payout_batch_items_self_select ON public.payout_batch_items;
CREATE POLICY payout_batch_items_self_select
ON public.payout_batch_items
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.payout_intents intent
    WHERE intent.id = payout_batch_items.payout_intent_id
      AND intent.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS payout_reconciliation_events_self_select ON public.payout_reconciliation_events;
CREATE POLICY payout_reconciliation_events_self_select
ON public.payout_reconciliation_events
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.payout_intents intent
    WHERE intent.id = payout_reconciliation_events.payout_intent_id
      AND intent.user_id = auth.uid()
  )
);
