ALTER TABLE public.monthly_cycle_events
DROP CONSTRAINT IF EXISTS monthly_cycle_events_event_type_check;

ALTER TABLE public.monthly_cycle_events
ADD CONSTRAINT monthly_cycle_events_event_type_check CHECK (
  event_type IN (
    'lock_attempt',
    'lock_success',
    'lock_failure',
    'prep_review',
    'prep_exception',
    'calculation_package_attempt',
    'calculation_package_success',
    'calculation_package_failure',
    'verification_review',
    'approval_review',
    'attribution_dataset_review',
    'bookkeeping_credits_create_attempt',
    'bookkeeping_credits_create_success',
    'bookkeeping_credits_create_failure',
    'payout_intents_create_attempt',
    'payout_intents_create_success',
    'payout_intents_create_failure',
    'payout_execution_attempt',
    'payout_execution_success',
    'payout_execution_failure',
    'reporting_publication_attempt',
    'reporting_publication_success',
    'reporting_publication_failure'
  )
);

CREATE TABLE IF NOT EXISTS public.monthly_cycle_bookkeeping_credits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monthly_cycle_id bigint NOT NULL REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  source_result_id bigint NOT NULL REFERENCES public.zkas_run_results(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'credited',
  payment_status text NOT NULL DEFAULT 'not_paid',
  usd_equivalent_amount numeric(20, 6) NOT NULL,
  currency_code text NOT NULL DEFAULT 'USD',
  asset_fills jsonb NOT NULL DEFAULT '[]',
  source_breakdown jsonb NOT NULL DEFAULT '[]',
  allocation_breakdown jsonb NOT NULL DEFAULT '{}',
  idempotency_key text NOT NULL UNIQUE,
  credited_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  credited_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT monthly_cycle_bookkeeping_credits_status_check CHECK (status IN ('credited', 'voided')),
  CONSTRAINT monthly_cycle_bookkeeping_credits_payment_status_check CHECK (payment_status IN ('not_paid')),
  CONSTRAINT monthly_cycle_bookkeeping_credits_usd_amount_check CHECK (usd_equivalent_amount >= 0),
  CONSTRAINT monthly_cycle_bookkeeping_credits_currency_code_check CHECK (currency_code ~ '^[A-Z]{3,12}$'),
  CONSTRAINT monthly_cycle_bookkeeping_credits_asset_fills_array_check CHECK (jsonb_typeof(asset_fills) = 'array'),
  CONSTRAINT monthly_cycle_bookkeeping_credits_source_breakdown_array_check CHECK (jsonb_typeof(source_breakdown) = 'array'),
  CONSTRAINT monthly_cycle_bookkeeping_credits_allocation_breakdown_object_check CHECK (jsonb_typeof(allocation_breakdown) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_cycle_bookkeeping_credits_source_result
ON public.monthly_cycle_bookkeeping_credits (source_result_id);

CREATE INDEX IF NOT EXISTS idx_monthly_cycle_bookkeeping_credits_cycle_user
ON public.monthly_cycle_bookkeeping_credits (monthly_cycle_id, user_id);

CREATE INDEX IF NOT EXISTS idx_monthly_cycle_bookkeeping_credits_user_created
ON public.monthly_cycle_bookkeeping_credits (user_id, credited_at DESC);

DROP TRIGGER IF EXISTS set_monthly_cycle_bookkeeping_credits_updated_at ON public.monthly_cycle_bookkeeping_credits;
CREATE TRIGGER set_monthly_cycle_bookkeeping_credits_updated_at
BEFORE UPDATE ON public.monthly_cycle_bookkeeping_credits
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.monthly_cycle_bookkeeping_credits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS monthly_cycle_bookkeeping_credits_self_select ON public.monthly_cycle_bookkeeping_credits;
CREATE POLICY monthly_cycle_bookkeeping_credits_self_select
ON public.monthly_cycle_bookkeeping_credits
FOR SELECT
USING (auth.uid() = user_id);
