DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_asset_preference_type') THEN
    CREATE TYPE public.user_asset_preference_type AS ENUM ('project_token', 'stablecoin', 'fiat');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.user_asset_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  rank integer NOT NULL,
  asset_type public.user_asset_preference_type NOT NULL,
  asset_code text NOT NULL,
  project_id bigint REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
  accepted boolean NOT NULL DEFAULT true,
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_asset_preferences_rank_check CHECK (rank > 0),
  CONSTRAINT user_asset_preferences_asset_code_check CHECK (asset_code ~ '^[A-Z0-9]{2,32}$'),
  CONSTRAINT user_asset_preferences_project_scope_check CHECK (
    (asset_type = 'project_token' AND project_id IS NOT NULL)
    OR (asset_type <> 'project_token' AND project_id IS NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_asset_preferences_user_rank
ON public.user_asset_preferences (user_id, rank);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_asset_preferences_user_asset
ON public.user_asset_preferences (user_id, asset_type, asset_code, COALESCE(project_id, 0));

CREATE INDEX IF NOT EXISTS idx_user_asset_preferences_user_accepted_rank
ON public.user_asset_preferences (user_id, accepted DESC, rank);

CREATE INDEX IF NOT EXISTS idx_user_asset_preferences_project
ON public.user_asset_preferences (project_id)
WHERE project_id IS NOT NULL;

DROP TRIGGER IF EXISTS set_user_asset_preferences_updated_at ON public.user_asset_preferences;
CREATE TRIGGER set_user_asset_preferences_updated_at
BEFORE UPDATE ON public.user_asset_preferences
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.user_asset_preferences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_asset_preferences_self_select ON public.user_asset_preferences;
CREATE POLICY user_asset_preferences_self_select
ON public.user_asset_preferences
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS user_asset_preferences_self_insert ON public.user_asset_preferences;
CREATE POLICY user_asset_preferences_self_insert
ON public.user_asset_preferences
FOR INSERT
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_asset_preferences_self_update ON public.user_asset_preferences;
CREATE POLICY user_asset_preferences_self_update
ON public.user_asset_preferences
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS user_asset_preferences_self_delete ON public.user_asset_preferences;
CREATE POLICY user_asset_preferences_self_delete
ON public.user_asset_preferences
FOR DELETE
USING (auth.uid() = user_id);
