DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'monthly_cycle_report_audience') THEN
    CREATE TYPE public.monthly_cycle_report_audience AS ENUM ('public', 'user', 'founder', 'operator');
  END IF;
END
$$;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'monthly-cycle-reports',
  'monthly-cycle-reports',
  false,
  20971520,
  ARRAY['application/json', 'text/markdown', 'application/pdf']
)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.monthly_cycle_reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monthly_cycle_id bigint NOT NULL REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE CASCADE,
  audience public.monthly_cycle_report_audience NOT NULL,
  subject_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  subject_project_id bigint REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
  title text NOT NULL,
  summary text NOT NULL DEFAULT '',
  artifact_bucket text NOT NULL DEFAULT 'monthly-cycle-reports',
  artifact_path text,
  artifact_mime_type text,
  artifact_hash text,
  payload jsonb NOT NULL DEFAULT '{}',
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT monthly_cycle_reports_subject_check CHECK (
    (audience = 'public' AND subject_user_id IS NULL AND subject_project_id IS NULL)
    OR (audience = 'operator' AND subject_user_id IS NULL AND subject_project_id IS NULL)
    OR (audience = 'user' AND subject_user_id IS NOT NULL AND subject_project_id IS NULL)
    OR (audience = 'founder' AND subject_user_id IS NULL AND subject_project_id IS NOT NULL)
  ),
  CONSTRAINT monthly_cycle_reports_artifact_pair_check CHECK (
    (artifact_path IS NULL AND artifact_hash IS NULL)
    OR artifact_path IS NOT NULL
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_cycle_reports_public_once
ON public.monthly_cycle_reports (monthly_cycle_id, audience)
WHERE audience IN ('public', 'operator');

CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_cycle_reports_user_once
ON public.monthly_cycle_reports (monthly_cycle_id, subject_user_id)
WHERE audience = 'user';

CREATE UNIQUE INDEX IF NOT EXISTS idx_monthly_cycle_reports_project_once
ON public.monthly_cycle_reports (monthly_cycle_id, subject_project_id)
WHERE audience = 'founder';

CREATE INDEX IF NOT EXISTS idx_monthly_cycle_reports_audience_published
ON public.monthly_cycle_reports (audience, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_monthly_cycle_reports_cycle
ON public.monthly_cycle_reports (monthly_cycle_id, audience);

DROP TRIGGER IF EXISTS set_monthly_cycle_reports_updated_at ON public.monthly_cycle_reports;
CREATE TRIGGER set_monthly_cycle_reports_updated_at
BEFORE UPDATE ON public.monthly_cycle_reports
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.monthly_cycle_reports ENABLE ROW LEVEL SECURITY;
