ALTER TABLE public.users
ADD COLUMN profile_headline text;

CREATE TABLE public.user_onboarding_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES public.users (user_id) ON DELETE CASCADE,
  current_screen text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone
);

CREATE TABLE public.project_onboarding_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL UNIQUE REFERENCES public.users (user_id) ON DELETE CASCADE,
  current_screen text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone
);

CREATE INDEX idx_user_onboarding_drafts_user_id
ON public.user_onboarding_drafts (user_id);

CREATE INDEX idx_project_onboarding_drafts_user_id
ON public.project_onboarding_drafts (user_id);

CREATE TRIGGER set_user_onboarding_drafts_updated_at
BEFORE UPDATE ON public.user_onboarding_drafts
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_project_onboarding_drafts_updated_at
BEFORE UPDATE ON public.project_onboarding_drafts
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.user_onboarding_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_onboarding_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_onboarding_drafts_owner_select
ON public.user_onboarding_drafts
FOR SELECT
USING (user_id = auth.uid());

CREATE POLICY user_onboarding_drafts_owner_insert
ON public.user_onboarding_drafts
FOR INSERT
WITH CHECK (user_id = auth.uid());

CREATE POLICY user_onboarding_drafts_owner_update
ON public.user_onboarding_drafts
FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY user_onboarding_drafts_owner_delete
ON public.user_onboarding_drafts
FOR DELETE
USING (user_id = auth.uid());

CREATE POLICY project_onboarding_drafts_owner_select
ON public.project_onboarding_drafts
FOR SELECT
USING (user_id = auth.uid());

CREATE POLICY project_onboarding_drafts_owner_insert
ON public.project_onboarding_drafts
FOR INSERT
WITH CHECK (user_id = auth.uid());

CREATE POLICY project_onboarding_drafts_owner_update
ON public.project_onboarding_drafts
FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY project_onboarding_drafts_owner_delete
ON public.project_onboarding_drafts
FOR DELETE
USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.create_user_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.users (
    user_id,
    created_at,
    updated_at,
    status,
    primary_email_identity
  )
  VALUES (
    NEW.id,
    now() AT TIME ZONE 'utc',
    now() AT TIME ZONE 'utc',
    'inactive',
    (
      SELECT id
      FROM auth.identities
      WHERE user_id = NEW.id
      ORDER BY (provider = 'email') DESC, created_at ASC
      LIMIT 1
    )
  );

  RETURN NEW;
EXCEPTION WHEN others THEN
  INSERT INTO public.debug_log (message)
  VALUES (
    'create_user_profile failed: user_id=' || NEW.id ||
    ', error=' || SQLERRM
  );

  RETURN NEW;
END;
$$;
