CREATE TYPE public.zkas_verification_status AS ENUM ('pending', 'verified', 'rejected');

ALTER TABLE public.zkas_runs
ADD COLUMN verification_status public.zkas_verification_status NOT NULL DEFAULT 'pending',
ADD COLUMN verified_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
ADD COLUMN verified_at timestamp with time zone,
ADD COLUMN verification_note text,
ADD COLUMN published_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
ADD COLUMN published_at timestamp with time zone,
ADD COLUMN publication_note text;

ALTER TABLE public.zkas_run_payments
ADD COLUMN project_id integer;

UPDATE public.zkas_run_payments zrp
SET project_id = p.project_id
FROM public.payments p
WHERE p.id = zrp.payment_id;

ALTER TABLE public.zkas_run_payments
ALTER COLUMN project_id SET NOT NULL;

ALTER TABLE public.zkas_run_payments
ADD CONSTRAINT zkas_run_payments_project_id_fkey
FOREIGN KEY (project_id) REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE INDEX idx_zkas_run_payments_run_project ON public.zkas_run_payments (run_id, project_id);
CREATE INDEX idx_zkas_runs_verification_status ON public.zkas_runs (verification_status, published_at, created_at DESC);

CREATE TABLE public.zkas_published_user_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
  zkas_user_id text NOT NULL,
  allocation_usd numeric(20, 6) NOT NULL,
  aggregate_score numeric(20, 6) NOT NULL,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  notification_id bigint REFERENCES public.user_notifications(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_published_user_results_run_user_key UNIQUE (run_id, user_id),
  CONSTRAINT zkas_published_user_results_run_zkas_user_key UNIQUE (run_id, zkas_user_id)
);

CREATE TABLE public.zkas_run_project_summaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  dataset_id bigint NOT NULL REFERENCES public.zkas_datasets(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  contributed_amount_usd numeric(20, 6) NOT NULL DEFAULT 0,
  active_user_count integer NOT NULL DEFAULT 0,
  avg_contribution_per_active_user_usd numeric(20, 6) NOT NULL DEFAULT 0,
  published_user_count integer NOT NULL DEFAULT 0,
  attributed_payout_usd numeric(20, 6) NOT NULL DEFAULT 0,
  avg_attributed_payout_per_published_user_usd numeric(20, 6) NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_run_project_summaries_run_project_key UNIQUE (run_id, project_id)
);

CREATE TABLE public.zkas_run_project_cubid_buckets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  project_id integer NOT NULL REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  bucket_key text NOT NULL,
  bucket_label text NOT NULL,
  user_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_run_project_cubid_buckets_run_project_bucket_key UNIQUE (run_id, project_id, bucket_key)
);

CREATE INDEX idx_zkas_published_user_results_user_id ON public.zkas_published_user_results (user_id, published_at DESC);
CREATE INDEX idx_zkas_run_project_summaries_run_id ON public.zkas_run_project_summaries (run_id, project_id);
CREATE INDEX idx_zkas_run_project_cubid_buckets_run_id ON public.zkas_run_project_cubid_buckets (run_id, project_id);

INSERT INTO public.ref_notification_types (name, code, description, display_order)
VALUES (
  'zkAS Published Result',
  'zkas_published_result',
  'Notifies a user that a verified zkActivitySum allocation has been published.',
  200
)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.zkas_published_user_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_run_project_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_run_project_cubid_buckets ENABLE ROW LEVEL SECURITY;

CREATE POLICY zkas_published_user_results_self_select
ON public.zkas_published_user_results
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY zkas_runs_self_published_select
ON public.zkas_runs
FOR SELECT
USING (
  published_at IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM public.zkas_published_user_results zpur
    WHERE zpur.run_id = public.zkas_runs.id
      AND zpur.user_id = auth.uid()
  )
);
