CREATE FUNCTION public.enforce_ledger_reference_posting_context()RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
DECLARE r public.financial_references%ROWTYPE;
BEGIN IF NEW.financial_reference_id IS NULL THEN RETURN NEW;END IF;SELECT * INTO r FROM public.financial_references WHERE id=NEW.financial_reference_id;
 IF NOT EXISTS(SELECT 1 FROM public.ledger_postings WHERE transaction_id=NEW.id AND native_atomic_amount IS NOT NULL)
 OR EXISTS(SELECT 1 FROM public.ledger_postings WHERE transaction_id=NEW.id AND(native_atomic_amount IS NULL OR asset_id IS DISTINCT FROM r.asset_id OR custody_account_id IS DISTINCT FROM r.custody_account_id))THEN RAISE EXCEPTION'ledger_reference_posting_context_mismatch';END IF;RETURN NEW;END $$;
CREATE CONSTRAINT TRIGGER ledger_reference_posting_context AFTER INSERT ON public.ledger_transactions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.enforce_ledger_reference_posting_context();

CREATE OR REPLACE FUNCTION public.claim_epoch_shadow_attempt(p_worker_id text,p_now timestamptz,p_deployment_environment text)RETURNS TABLE(attempt_id bigint,claim_token uuid,shadow_state_id bigint,target_stage text,expected_stage text,expected_state_version bigint,input_manifest_hash text)LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
BEGIN IF lower(p_deployment_environment)='production'OR NOT EXISTS(SELECT 1 FROM public.epoch_shadow_runtime_controls WHERE deployment_environment=lower(p_deployment_environment)AND scheduler_enabled AND NOT production_value_flow_enabled)THEN RAISE EXCEPTION'epoch_shadow_runtime_disabled';END IF;
 UPDATE public.epoch_stage_attempts SET status='queued',claim_token=NULL,worker_id=NULL,started_at=NULL WHERE status='claimed'AND started_at<=p_now-interval'5 minutes';
 RETURN QUERY UPDATE public.epoch_stage_attempts a SET status='claimed',claim_token=extensions.gen_random_uuid(),worker_id=p_worker_id,started_at=p_now WHERE a.id=(SELECT q.id FROM public.epoch_stage_attempts q JOIN public.epoch_shadow_states s ON s.id=q.shadow_state_id WHERE q.status='queued'AND q.scheduled_for<=p_now AND NOT s.is_paused ORDER BY q.scheduled_for,q.id FOR UPDATE OF q SKIP LOCKED LIMIT 1)RETURNING a.id,a.claim_token,a.shadow_state_id,a.target_stage,a.expected_stage,a.expected_state_version,a.input_manifest_hash;END $$;

CREATE OR REPLACE FUNCTION public.ingest_external_financial_event(p_provider_key text,p_provider_event_id text,p_custody_account_id bigint,p_asset_id bigint,p_event_type text,p_provider_sequence bigint,p_settled_native_amount numeric,p_occurred_at timestamptz,p_evidence_hash text,p_legacy_timestamp_evidence jsonb,p_deployment_environment text)RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE e public.external_financial_events%ROWTYPE;v_id bigint;v_order text;v_legacy jsonb:=coalesce(p_legacy_timestamp_evidence,'{}');BEGIN IF lower(coalesce(p_deployment_environment,''))NOT IN('local','dev','test')THEN RAISE EXCEPTION'shadow_reconciliation_disabled';END IF;
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_provider_key||':custody:'||p_custody_account_id::text,0));
 PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_provider_key||':event:'||p_provider_event_id,0));SELECT * INTO e FROM public.external_financial_events WHERE provider_key=p_provider_key AND provider_event_id=p_provider_event_id;
 IF FOUND THEN IF e.custody_account_id<>p_custody_account_id OR e.asset_id<>p_asset_id OR e.event_type<>p_event_type OR e.provider_sequence IS DISTINCT FROM p_provider_sequence OR e.settled_native_amount<>p_settled_native_amount OR e.occurred_at<>p_occurred_at OR e.evidence_hash<>p_evidence_hash OR e.legacy_timestamp_evidence<>v_legacy THEN RAISE EXCEPTION'external_event_dedupe_conflict';END IF;RETURN e.id;END IF;
 v_order:=CASE WHEN p_provider_sequence IS NULL THEN'unsequenced'WHEN EXISTS(SELECT 1 FROM public.external_financial_events WHERE provider_key=p_provider_key AND custody_account_id=p_custody_account_id AND provider_sequence>=p_provider_sequence)THEN'out_of_order'ELSE'in_order'END;INSERT INTO public.external_financial_events(provider_key,provider_event_id,custody_account_id,asset_id,event_type,provider_sequence,settled_native_amount,occurred_at,ordering_status,evidence_hash,legacy_timestamp_evidence)VALUES(p_provider_key,p_provider_event_id,p_custody_account_id,p_asset_id,p_event_type,p_provider_sequence,p_settled_native_amount,p_occurred_at,v_order,p_evidence_hash,v_legacy)RETURNING id INTO v_id;RETURN v_id;END $$;
