CREATE TYPE public.payment_collection_mode AS ENUM ('contract', 'deposit_address');

ALTER TABLE public.ref_chains
  ADD COLUMN display_name text,
  ADD COLUMN ecosystem text,
  ADD COLUMN network_key text,
  ADD COLUMN evm_chain_id bigint,
  ADD COLUMN layer_type text,
  ADD COLUMN native_asset_symbol text,
  ADD COLUMN is_active boolean NOT NULL DEFAULT true;

UPDATE public.ref_chains
SET
  display_name = COALESCE(display_name, 'Ethereum'),
  ecosystem = COALESCE(ecosystem, 'evm'),
  network_key = COALESCE(network_key, 'ethereum'),
  evm_chain_id = COALESCE(evm_chain_id, 1),
  layer_type = COALESCE(layer_type, 'L1'),
  native_asset_symbol = COALESCE(native_asset_symbol, 'ETH'),
  is_active = COALESCE(is_active, true)
WHERE chain_id = '1' OR lower(description) = 'ethereum';

INSERT INTO public.ref_chains (
  chain_id,
  description,
  display_name,
  ecosystem,
  network_key,
  evm_chain_id,
  layer_type,
  native_asset_symbol,
  is_active
)
SELECT * FROM (
  VALUES
    ('8453', 'base', 'Base', 'evm', 'base', 8453, 'L2', 'ETH', true),
    ('42220', 'celo', 'Celo', 'evm', 'celo', 42220, 'L1', 'CELO', true)
) AS rows(chain_id, description, display_name, ecosystem, network_key, evm_chain_id, layer_type, native_asset_symbol, is_active)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.ref_chains existing
  WHERE existing.evm_chain_id = rows.evm_chain_id
     OR existing.network_key = rows.network_key
);

ALTER TABLE public.ref_chains
  ALTER COLUMN display_name SET NOT NULL,
  ALTER COLUMN ecosystem SET NOT NULL,
  ALTER COLUMN network_key SET NOT NULL,
  ALTER COLUMN evm_chain_id SET NOT NULL,
  ALTER COLUMN layer_type SET NOT NULL,
  ALTER COLUMN native_asset_symbol SET NOT NULL;

CREATE UNIQUE INDEX ref_chains_network_key_key ON public.ref_chains (network_key);
CREATE UNIQUE INDEX ref_chains_evm_chain_id_key ON public.ref_chains (evm_chain_id);

CREATE TABLE public.ref_chain_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain_id bigint NOT NULL REFERENCES public.ref_chains(id) ON DELETE CASCADE,
  asset_key text NOT NULL,
  symbol text NOT NULL,
  name text NOT NULL,
  token_address text,
  decimals integer NOT NULL,
  is_native boolean NOT NULL DEFAULT false,
  is_stablecoin boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ref_chain_assets_asset_key_key UNIQUE (chain_id, asset_key),
  CONSTRAINT ref_chain_assets_native_token_address_check CHECK (
    (is_native = true AND token_address IS NULL) OR
    (is_native = false AND token_address IS NOT NULL)
  )
);

CREATE TABLE public.chain_intake_contracts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain_id bigint NOT NULL REFERENCES public.ref_chains(id) ON DELETE CASCADE,
  collection_mode public.payment_collection_mode NOT NULL DEFAULT 'contract',
  contract_address text NOT NULL,
  treasury_address text NOT NULL,
  abi_version text NOT NULL DEFAULT 'fundloop-intake-v1',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT chain_intake_contracts_chain_mode_key UNIQUE (chain_id, collection_mode)
);

CREATE TRIGGER set_chain_intake_contracts_updated_at
BEFORE UPDATE ON public.chain_intake_contracts
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.payment_methods
  ADD COLUMN collection_mode public.payment_collection_mode NOT NULL DEFAULT 'deposit_address',
  ADD COLUMN chain_id bigint REFERENCES public.ref_chains(id) ON UPDATE CASCADE,
  ADD COLUMN chain_asset_id bigint REFERENCES public.ref_chain_assets(id) ON UPDATE CASCADE,
  ADD COLUMN intake_contract_id bigint REFERENCES public.chain_intake_contracts(id) ON UPDATE CASCADE,
  ADD COLUMN label text,
  ADD COLUMN is_enabled boolean NOT NULL DEFAULT true,
  ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT now();

DROP TRIGGER IF EXISTS set_payment_methods_updated_at ON public.payment_methods;

CREATE TRIGGER set_payment_methods_updated_at
BEFORE UPDATE ON public.payment_methods
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE UNIQUE INDEX idx_payment_methods_single_default
ON public.payment_methods (project_id)
WHERE is_default = true AND is_enabled = true;

CREATE TABLE public.onchain_payment_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id bigint REFERENCES public.payments(id) ON DELETE SET NULL,
  project_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  payment_method_id bigint NOT NULL REFERENCES public.payment_methods(id) ON DELETE CASCADE,
  chain_id bigint NOT NULL REFERENCES public.ref_chains(id) ON DELETE RESTRICT,
  chain_asset_id bigint NOT NULL REFERENCES public.ref_chain_assets(id) ON DELETE RESTRICT,
  intake_contract_id bigint NOT NULL REFERENCES public.chain_intake_contracts(id) ON DELETE RESTRICT,
  wallet_address text NOT NULL,
  tx_hash text NOT NULL UNIQUE,
  amount_raw text NOT NULL,
  amount_decimal numeric(38, 18) NOT NULL,
  status text NOT NULL DEFAULT 'submitted',
  block_number bigint,
  metadata jsonb,
  receipt jsonb,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  confirmed_at timestamp with time zone
);

CREATE INDEX idx_onchain_payment_submissions_project_id
ON public.onchain_payment_submissions (project_id, submitted_at DESC);

CREATE INDEX idx_onchain_payment_submissions_payment_id
ON public.onchain_payment_submissions (payment_id);

do $$
declare
  current_method_id integer;
  reserved_method_id constant integer := 999;
begin
  select id
  into current_method_id
  from public.ref_payment_methods
  where code = 'crypto_contract';

  if current_method_id is null then
    insert into public.ref_payment_methods (id, name, code, description, display_order)
    overriding system value
    values (
      reserved_method_id,
      'Crypto Contract',
      'crypto_contract',
      'Pay through a supported FundLoop intake contract and tag the payment with your project ID.',
      50
    );
  elsif current_method_id <> reserved_method_id then
    if exists (
      select 1
      from public.ref_payment_methods
      where id = reserved_method_id
        and code <> 'crypto_contract'
    ) then
      raise exception 'ref_payment_methods id % is already in use by a different method', reserved_method_id;
    end if;

    update public.ref_payment_methods
    set
      name = format('Crypto Contract Legacy %s', current_method_id),
      code = format('crypto_contract_legacy_%s', current_method_id)
    where id = current_method_id;

    insert into public.ref_payment_methods (id, name, code, description, display_order)
    overriding system value
    values (
      reserved_method_id,
      'Crypto Contract',
      'crypto_contract',
      'Pay through a supported FundLoop intake contract and tag the payment with your project ID.',
      50
    );

    update public.payment_methods
    set method_id = reserved_method_id
    where method_id = current_method_id;

    update public.payments
    set payment_method_id = reserved_method_id
    where payment_method_id = current_method_id;

    update public.projects
    set default_payment_method_id = reserved_method_id
    where default_payment_method_id = current_method_id;

    delete from public.ref_payment_methods
    where id = current_method_id;
  else
    update public.ref_payment_methods
    set
      name = 'Crypto Contract',
      description = 'Pay through a supported FundLoop intake contract and tag the payment with your project ID.',
      display_order = 50
    where id = reserved_method_id;
  end if;

  perform setval(
    pg_get_serial_sequence('public.ref_payment_methods', 'id'),
    greatest(
      reserved_method_id,
      coalesce((select max(id) from public.ref_payment_methods), reserved_method_id)
    ),
    true
  );
end
$$;

INSERT INTO public.ref_chain_assets (
  chain_id,
  asset_key,
  symbol,
  name,
  token_address,
  decimals,
  is_native,
  is_stablecoin,
  is_active,
  sort_order
)
SELECT chains.id, assets.asset_key, assets.symbol, assets.name, assets.token_address, assets.decimals, assets.is_native, assets.is_stablecoin, true, assets.sort_order
FROM (
  VALUES
    ('ethereum', 'native', 'ETH', 'Ether', NULL, 18, true, false, 0),
    ('ethereum', 'usdc', 'USDC', 'USD Coin', '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 6, false, true, 1),
    ('base', 'native', 'ETH', 'Ether', NULL, 18, true, false, 0),
    ('base', 'usdc', 'USDC', 'USD Coin', '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', 6, false, true, 1),
    ('celo', 'native', 'CELO', 'Celo Native Asset', NULL, 18, true, false, 0),
    ('celo', 'usdc', 'USDC', 'USD Coin', '0xcebA9300f2b948710d2653dD7B07f33A8B32118C', 6, false, true, 1)
) AS assets(network_key, asset_key, symbol, name, token_address, decimals, is_native, is_stablecoin, sort_order)
JOIN public.ref_chains chains ON chains.network_key = assets.network_key
ON CONFLICT (chain_id, asset_key) DO UPDATE
SET
  symbol = EXCLUDED.symbol,
  name = EXCLUDED.name,
  token_address = EXCLUDED.token_address,
  decimals = EXCLUDED.decimals,
  is_native = EXCLUDED.is_native,
  is_stablecoin = EXCLUDED.is_stablecoin,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

WITH intake_settings AS (
  SELECT
    chains.id AS chain_id,
    'contract'::public.payment_collection_mode AS collection_mode,
    CASE chains.network_key
      WHEN 'ethereum' THEN COALESCE(NULLIF(current_setting('app.settings.ethereum_intake_contract', true), ''), '0x0000000000000000000000000000000000000000')
      WHEN 'base' THEN COALESCE(NULLIF(current_setting('app.settings.base_intake_contract', true), ''), '0x0000000000000000000000000000000000000000')
      WHEN 'celo' THEN COALESCE(NULLIF(current_setting('app.settings.celo_intake_contract', true), ''), '0x0000000000000000000000000000000000000000')
    END AS contract_address,
    CASE chains.network_key
      WHEN 'ethereum' THEN COALESCE(NULLIF(current_setting('app.settings.ethereum_treasury_address', true), ''), '0x0000000000000000000000000000000000000000')
      WHEN 'base' THEN COALESCE(NULLIF(current_setting('app.settings.base_treasury_address', true), ''), '0x0000000000000000000000000000000000000000')
      WHEN 'celo' THEN COALESCE(NULLIF(current_setting('app.settings.celo_treasury_address', true), ''), '0x0000000000000000000000000000000000000000')
    END AS treasury_address,
    'fundloop-intake-v1'::text AS abi_version
  FROM public.ref_chains chains
  WHERE chains.network_key IN ('ethereum', 'base', 'celo')
)
INSERT INTO public.chain_intake_contracts (
  chain_id,
  collection_mode,
  contract_address,
  treasury_address,
  abi_version,
  is_active
)
SELECT
  settings.chain_id,
  settings.collection_mode,
  settings.contract_address,
  settings.treasury_address,
  settings.abi_version,
  settings.contract_address <> '0x0000000000000000000000000000000000000000'
    AND settings.treasury_address <> '0x0000000000000000000000000000000000000000'
FROM intake_settings settings
ON CONFLICT (chain_id, collection_mode) DO UPDATE
SET
  contract_address = EXCLUDED.contract_address,
  treasury_address = EXCLUDED.treasury_address,
  abi_version = EXCLUDED.abi_version,
  is_active = EXCLUDED.is_active;
