ALTER TABLE public.monthly_cycles
ADD COLUMN IF NOT EXISTS locked_manifest jsonb,
ADD COLUMN IF NOT EXISTS locked_manifest_hash text,
ADD COLUMN IF NOT EXISTS locked_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS lock_override_unresolved_onchain boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS lock_override_reason text;

CREATE INDEX IF NOT EXISTS idx_monthly_cycles_locked_manifest_hash
ON public.monthly_cycles (locked_manifest_hash)
WHERE locked_manifest_hash IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.monthly_cycle_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL,
  cycle_key text NOT NULL,
  event_type text NOT NULL,
  attempt_id text NOT NULL,
  actor_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  actor_role text NOT NULL,
  outcome text NOT NULL,
  severity text NOT NULL DEFAULT 'info',
  message text,
  metadata jsonb NOT NULL DEFAULT '{}',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT monthly_cycle_events_cycle_key_format_check CHECK (cycle_key ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT monthly_cycle_events_event_type_check CHECK (event_type IN ('lock_attempt', 'lock_success', 'lock_failure')),
  CONSTRAINT monthly_cycle_events_outcome_check CHECK (outcome IN ('attempt', 'success', 'failure')),
  CONSTRAINT monthly_cycle_events_severity_check CHECK (severity IN ('info', 'warning', 'error')),
  CONSTRAINT monthly_cycle_events_actor_role_check CHECK (actor_role IN ('internal_admin', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_monthly_cycle_events_cycle_created
ON public.monthly_cycle_events (monthly_cycle_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_monthly_cycle_events_attempt_id
ON public.monthly_cycle_events (attempt_id);

ALTER TABLE public.monthly_cycle_events ENABLE ROW LEVEL SECURITY;
