DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'monthly_cycle_status') THEN
    CREATE TYPE public.monthly_cycle_status AS ENUM (
      'open',
      'locked',
      'prep',
      'calculation',
      'verification',
      'approval',
      'distribution',
      'completed',
      'reporting'
    );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.monthly_cycles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_key text NOT NULL UNIQUE,
  year smallint NOT NULL,
  month smallint NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  status public.monthly_cycle_status NOT NULL DEFAULT 'open',
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  locked_at timestamp with time zone,
  prep_started_at timestamp with time zone,
  calculation_started_at timestamp with time zone,
  verification_started_at timestamp with time zone,
  approval_started_at timestamp with time zone,
  distribution_started_at timestamp with time zone,
  completed_at timestamp with time zone,
  reporting_published_at timestamp with time zone,
  operator_note text,
  status_note text,
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  updated_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT monthly_cycles_cycle_key_format_check CHECK (cycle_key ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT monthly_cycles_year_month_check CHECK (
    year = split_part(cycle_key, '-', 1)::smallint
    AND month = split_part(cycle_key, '-', 2)::smallint
  ),
  CONSTRAINT monthly_cycles_month_bounds_check CHECK (
    month BETWEEN 1 AND 12
    AND period_start = make_date(year::integer, month::integer, 1)
    AND period_end = (make_date(year::integer, month::integer, 1) + interval '1 month - 1 day')::date
  ),
  CONSTRAINT monthly_cycles_year_month_key UNIQUE (year, month)
);

CREATE INDEX IF NOT EXISTS idx_monthly_cycles_status
ON public.monthly_cycles (status, period_start DESC);

CREATE INDEX IF NOT EXISTS idx_monthly_cycles_period
ON public.monthly_cycles (period_start DESC);

DROP TRIGGER IF EXISTS set_monthly_cycles_updated_at ON public.monthly_cycles;
CREATE TRIGGER set_monthly_cycles_updated_at
BEFORE UPDATE ON public.monthly_cycles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.monthly_cycles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.payments
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.onchain_payment_submissions
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.project_stats_monthly
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_identity_artifacts
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_datasets
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_runs
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_run_payments
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_run_attempts
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_run_results
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_published_user_results
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_run_project_summaries
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE public.zkas_run_project_cubid_buckets
ADD COLUMN IF NOT EXISTS monthly_cycle_id bigint REFERENCES public.monthly_cycles(id) ON UPDATE CASCADE ON DELETE SET NULL;

WITH cycle_sources AS (
  SELECT to_char(period_end, 'YYYY-MM') AS cycle_key
  FROM public.payments
  WHERE period_end IS NOT NULL

  UNION
  SELECT to_char(submitted_at, 'YYYY-MM') AS cycle_key
  FROM public.onchain_payment_submissions
  WHERE submitted_at IS NOT NULL

  UNION
  SELECT month AS cycle_key
  FROM public.zkas_identity_artifacts
  WHERE month ~ '^\d{4}-(0[1-9]|1[0-2])$'

  UNION
  SELECT month AS cycle_key
  FROM public.zkas_datasets
  WHERE month ~ '^\d{4}-(0[1-9]|1[0-2])$'

  UNION
  SELECT month AS cycle_key
  FROM public.zkas_runs
  WHERE month ~ '^\d{4}-(0[1-9]|1[0-2])$'

  UNION
  SELECT format('%s-%s', year, lpad(month::text, 2, '0')) AS cycle_key
  FROM public.project_stats_monthly
  WHERE year IS NOT NULL AND month BETWEEN 1 AND 12
)
INSERT INTO public.monthly_cycles (cycle_key, year, month, period_start, period_end)
SELECT
  cycle_key,
  split_part(cycle_key, '-', 1)::smallint AS year,
  split_part(cycle_key, '-', 2)::smallint AS month,
  to_date(cycle_key || '-01', 'YYYY-MM-DD') AS period_start,
  (to_date(cycle_key || '-01', 'YYYY-MM-DD') + interval '1 month - 1 day')::date AS period_end
FROM cycle_sources
WHERE cycle_key IS NOT NULL
ON CONFLICT (cycle_key) DO NOTHING;

UPDATE public.payments payment
SET monthly_cycle_id = cycle.id
FROM public.monthly_cycles cycle
WHERE payment.monthly_cycle_id IS NULL
  AND cycle.cycle_key = to_char(payment.period_end, 'YYYY-MM');

UPDATE public.onchain_payment_submissions submission
SET monthly_cycle_id = COALESCE(
  (SELECT payment.monthly_cycle_id FROM public.payments payment WHERE payment.id = submission.payment_id),
  submitted_cycle.id
)
FROM public.monthly_cycles submitted_cycle
WHERE submission.monthly_cycle_id IS NULL
  AND submitted_cycle.cycle_key = to_char(submission.submitted_at, 'YYYY-MM');

UPDATE public.project_stats_monthly stats
SET monthly_cycle_id = cycle.id
FROM public.monthly_cycles cycle
WHERE stats.monthly_cycle_id IS NULL
  AND stats.year IS NOT NULL
  AND stats.month BETWEEN 1 AND 12
  AND cycle.cycle_key = format('%s-%s', stats.year, lpad(stats.month::text, 2, '0'));

UPDATE public.zkas_identity_artifacts artifact
SET monthly_cycle_id = cycle.id
FROM public.monthly_cycles cycle
WHERE artifact.monthly_cycle_id IS NULL
  AND cycle.cycle_key = artifact.month;

UPDATE public.zkas_datasets dataset
SET monthly_cycle_id = cycle.id
FROM public.monthly_cycles cycle
WHERE dataset.monthly_cycle_id IS NULL
  AND cycle.cycle_key = dataset.month;

UPDATE public.zkas_runs run
SET monthly_cycle_id = cycle.id
FROM public.monthly_cycles cycle
WHERE run.monthly_cycle_id IS NULL
  AND cycle.cycle_key = run.month;

UPDATE public.zkas_run_payments run_payment
SET monthly_cycle_id = COALESCE(
  (SELECT payment.monthly_cycle_id FROM public.payments payment WHERE payment.id = run_payment.payment_id),
  cycle.id
)
FROM public.monthly_cycles cycle
WHERE run_payment.monthly_cycle_id IS NULL
  AND cycle.cycle_key = to_char(run_payment.period_end, 'YYYY-MM');

UPDATE public.zkas_run_attempts attempt
SET monthly_cycle_id = run.monthly_cycle_id
FROM public.zkas_runs run
WHERE attempt.monthly_cycle_id IS NULL
  AND run.id = attempt.run_id;

UPDATE public.zkas_run_results result
SET monthly_cycle_id = run.monthly_cycle_id
FROM public.zkas_runs run
WHERE result.monthly_cycle_id IS NULL
  AND run.id = result.run_id;

UPDATE public.zkas_published_user_results result
SET monthly_cycle_id = run.monthly_cycle_id
FROM public.zkas_runs run
WHERE result.monthly_cycle_id IS NULL
  AND run.id = result.run_id;

UPDATE public.zkas_run_project_summaries summary
SET monthly_cycle_id = run.monthly_cycle_id
FROM public.zkas_runs run
WHERE summary.monthly_cycle_id IS NULL
  AND run.id = summary.run_id;

UPDATE public.zkas_run_project_cubid_buckets bucket
SET monthly_cycle_id = run.monthly_cycle_id
FROM public.zkas_runs run
WHERE bucket.monthly_cycle_id IS NULL
  AND run.id = bucket.run_id;

CREATE INDEX IF NOT EXISTS idx_payments_monthly_cycle_id
ON public.payments (monthly_cycle_id, period_end DESC);

CREATE INDEX IF NOT EXISTS idx_onchain_payment_submissions_monthly_cycle_id
ON public.onchain_payment_submissions (monthly_cycle_id, submitted_at DESC);

CREATE INDEX IF NOT EXISTS idx_project_stats_monthly_monthly_cycle_id
ON public.project_stats_monthly (monthly_cycle_id, project_id);

CREATE INDEX IF NOT EXISTS idx_zkas_identity_artifacts_monthly_cycle_id
ON public.zkas_identity_artifacts (monthly_cycle_id);

CREATE INDEX IF NOT EXISTS idx_zkas_datasets_monthly_cycle_id
ON public.zkas_datasets (monthly_cycle_id, project_id);

CREATE INDEX IF NOT EXISTS idx_zkas_runs_monthly_cycle_id
ON public.zkas_runs (monthly_cycle_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_zkas_run_payments_monthly_cycle_id
ON public.zkas_run_payments (monthly_cycle_id, run_id);

CREATE INDEX IF NOT EXISTS idx_zkas_run_attempts_monthly_cycle_id
ON public.zkas_run_attempts (monthly_cycle_id, run_id);

CREATE INDEX IF NOT EXISTS idx_zkas_run_results_monthly_cycle_id
ON public.zkas_run_results (monthly_cycle_id, allocation_usd DESC);

CREATE INDEX IF NOT EXISTS idx_zkas_published_user_results_monthly_cycle_id
ON public.zkas_published_user_results (monthly_cycle_id, published_at DESC);

CREATE INDEX IF NOT EXISTS idx_zkas_run_project_summaries_monthly_cycle_id
ON public.zkas_run_project_summaries (monthly_cycle_id, project_id);

CREATE INDEX IF NOT EXISTS idx_zkas_run_project_cubid_buckets_monthly_cycle_id
ON public.zkas_run_project_cubid_buckets (monthly_cycle_id, project_id);
