CREATE TYPE public.zkas_dataset_status AS ENUM (
  'uploaded',
  'validated',
  'failed',
  'approved',
  'included',
  'replaced',
  'archived'
);

CREATE TYPE public.zkas_issue_severity AS ENUM ('error', 'warning');

CREATE TYPE public.zkas_run_status AS ENUM (
  'draft',
  'locked',
  'running',
  'completed',
  'failed',
  'finalized'
);

CREATE TYPE public.zkas_execution_mode AS ENUM ('local', 'nitro');

INSERT INTO public.ref_roles (name, display_order)
VALUES ('zkas_access', 90)
ON CONFLICT (name) DO NOTHING;

CREATE TABLE public.zkas_identity_artifacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month text NOT NULL,
  file_name text NOT NULL,
  object_path text NOT NULL UNIQUE,
  artifact_hash text NOT NULL UNIQUE,
  schema_version text NOT NULL DEFAULT 'zkas.v1',
  provider text NOT NULL DEFAULT 'cubid',
  note text,
  status text NOT NULL DEFAULT 'approved',
  uploaded_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_identity_artifacts_month_format_check CHECK (month ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

CREATE UNIQUE INDEX zkas_identity_artifacts_single_approved_month
ON public.zkas_identity_artifacts (month)
WHERE status = 'approved';

CREATE TABLE public.zkas_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month text NOT NULL,
  status public.zkas_run_status NOT NULL DEFAULT 'draft',
  usd_pool numeric(18, 6) NOT NULL DEFAULT 0,
  schema_version text NOT NULL DEFAULT 'zkas.v1',
  engine_git_ref text NOT NULL DEFAULT '',
  engine_image_ref text NOT NULL DEFAULT 'zkas/local',
  engine_config_version text NOT NULL DEFAULT 'local-v1',
  identity_artifact_id bigint REFERENCES public.zkas_identity_artifacts(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  locked_manifest jsonb,
  locked_manifest_hash text,
  result_artifact_path text,
  result_artifact_hash text,
  attestation_artifact_path text,
  attestation_artifact_hash text,
  total_score numeric(20, 6),
  total_allocated_usd numeric(20, 6),
  user_count integer,
  note text,
  created_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  locked_at timestamp with time zone,
  finalized_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_runs_month_format_check CHECK (month ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

CREATE TABLE public.zkas_datasets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
  month text NOT NULL,
  format text NOT NULL,
  file_name text NOT NULL,
  object_path text NOT NULL UNIQUE,
  file_hash text NOT NULL UNIQUE,
  schema_version text NOT NULL DEFAULT 'zkas.v1',
  row_count integer NOT NULL DEFAULT 0,
  status public.zkas_dataset_status NOT NULL DEFAULT 'uploaded',
  validation_summary jsonb,
  note text,
  uploaded_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  approved_by_user_id uuid REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
  approved_at timestamp with time zone,
  replaced_by_dataset_id bigint REFERENCES public.zkas_datasets(id) ON UPDATE CASCADE ON DELETE SET NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_datasets_month_format_check CHECK (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  CONSTRAINT zkas_datasets_format_check CHECK (format IN ('csv', 'json'))
);

CREATE UNIQUE INDEX zkas_datasets_single_active_approved
ON public.zkas_datasets (project_id, month)
WHERE status IN ('approved', 'included');

CREATE TABLE public.zkas_dataset_issues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id bigint NOT NULL REFERENCES public.zkas_datasets(id) ON UPDATE CASCADE ON DELETE CASCADE,
  severity public.zkas_issue_severity NOT NULL,
  code text NOT NULL,
  message text NOT NULL,
  row_number integer,
  field_name text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.zkas_run_datasets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  dataset_id bigint NOT NULL REFERENCES public.zkas_datasets(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  project_id integer NOT NULL REFERENCES public.projects(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  object_path text NOT NULL,
  file_hash text NOT NULL,
  row_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_run_datasets_run_dataset_key UNIQUE (run_id, dataset_id),
  CONSTRAINT zkas_run_datasets_run_project_key UNIQUE (run_id, project_id)
);

CREATE TABLE public.zkas_run_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  payment_id bigint NOT NULL REFERENCES public.payments(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  amount_usd numeric(18, 6) NOT NULL,
  period_end date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_run_payments_run_payment_key UNIQUE (run_id, payment_id)
);

CREATE TABLE public.zkas_run_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  mode public.zkas_execution_mode NOT NULL DEFAULT 'local',
  status text NOT NULL DEFAULT 'pending',
  worker_job_id text,
  logs text,
  failure_reason text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.zkas_run_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.zkas_runs(id) ON UPDATE CASCADE ON DELETE CASCADE,
  zkas_user_id text NOT NULL,
  eligibility boolean NOT NULL,
  aggregate_score numeric(20, 6) NOT NULL,
  allocation_usd numeric(20, 6) NOT NULL,
  app_count integer NOT NULL DEFAULT 0,
  project_count integer NOT NULL DEFAULT 0,
  output_row_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT zkas_run_results_run_user_key UNIQUE (run_id, zkas_user_id)
);

CREATE INDEX idx_zkas_datasets_project_month ON public.zkas_datasets (project_id, month, created_at DESC);
CREATE INDEX idx_zkas_runs_month_status ON public.zkas_runs (month, status, created_at DESC);
CREATE INDEX idx_zkas_run_attempts_run_id ON public.zkas_run_attempts (run_id, created_at DESC);
CREATE INDEX idx_zkas_run_results_run_id ON public.zkas_run_results (run_id, allocation_usd DESC);

CREATE OR REPLACE FUNCTION public.enforce_zkas_access_role_on_project_admins()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  zkas_role_id integer;
  participant_is_admin boolean;
BEGIN
  SELECT id INTO zkas_role_id
  FROM public.ref_roles
  WHERE name = 'zkas_access';

  IF zkas_role_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF NEW.role_id = zkas_role_id THEN
    SELECT is_admin INTO participant_is_admin
    FROM public.participants
    WHERE id = NEW.participant_id;

    IF participant_is_admin IS DISTINCT FROM true THEN
      RAISE EXCEPTION 'zkas_access can only be assigned to project admins';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.prevent_zkas_access_on_non_admin_participants()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  has_zkas_role boolean;
BEGIN
  IF OLD.is_admin = true AND NEW.is_admin = false THEN
    SELECT EXISTS (
      SELECT 1
      FROM public.participant_roles pr
      JOIN public.ref_roles rr ON rr.id = pr.role_id
      WHERE pr.participant_id = NEW.id
        AND rr.name = 'zkas_access'
    )
    INTO has_zkas_role;

    IF has_zkas_role THEN
      RAISE EXCEPTION 'Remove zkas_access before demoting this participant from project admin';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_zkas_access_role_on_project_admins
BEFORE INSERT OR UPDATE ON public.participant_roles
FOR EACH ROW
EXECUTE FUNCTION public.enforce_zkas_access_role_on_project_admins();

CREATE TRIGGER prevent_zkas_access_on_non_admin_participants
BEFORE UPDATE ON public.participants
FOR EACH ROW
EXECUTE FUNCTION public.prevent_zkas_access_on_non_admin_participants();

CREATE TRIGGER set_zkas_identity_artifacts_updated_at
BEFORE UPDATE ON public.zkas_identity_artifacts
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_zkas_runs_updated_at
BEFORE UPDATE ON public.zkas_runs
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_zkas_datasets_updated_at
BEFORE UPDATE ON public.zkas_datasets
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER audit_zkas_identity_artifacts
AFTER INSERT OR UPDATE OR DELETE ON public.zkas_identity_artifacts
FOR EACH ROW
EXECUTE FUNCTION public.log_changes();

CREATE TRIGGER audit_zkas_runs
AFTER INSERT OR UPDATE OR DELETE ON public.zkas_runs
FOR EACH ROW
EXECUTE FUNCTION public.log_changes();

CREATE TRIGGER audit_zkas_datasets
AFTER INSERT OR UPDATE OR DELETE ON public.zkas_datasets
FOR EACH ROW
EXECUTE FUNCTION public.log_changes();

CREATE TRIGGER audit_zkas_run_attempts
AFTER INSERT OR UPDATE OR DELETE ON public.zkas_run_attempts
FOR EACH ROW
EXECUTE FUNCTION public.log_changes();

ALTER TABLE public.zkas_identity_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_dataset_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_run_datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_run_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_run_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zkas_run_results ENABLE ROW LEVEL SECURITY;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('zkas-datasets', 'zkas-datasets', false, 10485760, ARRAY['text/csv', 'application/json']),
  ('zkas-identities', 'zkas-identities', false, 10485760, ARRAY['application/json']),
  ('zkas-runs', 'zkas-runs', false, 20971520, ARRAY['application/json', 'text/plain'])
ON CONFLICT (id) DO NOTHING;
