create table public.payment_flow_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  flow text not null check (
    flow in ('wallet_connect', 'payment_save', 'receipt_recording', 'admin_confirmation')
  ),
  stage text not null check (
    stage in (
      'cta_click',
      'runtime_blocked',
      'modal_open',
      'connected',
      'timeout',
      'validation',
      'submit',
      'chain_switch',
      'approval',
      'deposit',
      'submission_record'
    )
  ),
  outcome text not null check (outcome in ('attempt', 'success', 'failure')),
  severity text not null default 'info' check (severity in ('info', 'warning', 'error')),
  attempt_id text not null,
  actor_user_id text,
  actor_role text not null default 'authenticated_user' check (
    actor_role in ('unauthenticated', 'authenticated_user', 'project_admin', 'internal_admin')
  ),
  project_id integer references public.projects(id) on delete set null,
  payment_id integer references public.payments(id) on delete set null,
  submission_id integer references public.onchain_payment_submissions(id) on delete set null,
  payment_method_id integer references public.payment_methods(id) on delete set null,
  chain_id integer references public.ref_chains(id) on delete set null,
  chain_asset_id integer references public.ref_chain_assets(id) on delete set null,
  intake_contract_id integer references public.chain_intake_contracts(id) on delete set null,
  tx_hash text,
  wallet_address text,
  environment text not null check (environment in ('local', 'preview', 'production')),
  error_code text,
  error_message text,
  metadata jsonb not null default '{}'::jsonb
);

create index payment_flow_events_created_at_idx
  on public.payment_flow_events (created_at desc);

create index payment_flow_events_flow_created_at_idx
  on public.payment_flow_events (flow, created_at desc);

create index payment_flow_events_outcome_created_at_idx
  on public.payment_flow_events (outcome, created_at desc);

create index payment_flow_events_attempt_id_idx
  on public.payment_flow_events (attempt_id);

create index payment_flow_events_project_created_at_idx
  on public.payment_flow_events (project_id, created_at desc);

create index payment_flow_events_payment_created_at_idx
  on public.payment_flow_events (payment_id, created_at desc);

alter table public.payment_flow_events enable row level security;
